---
- name: Scaling service {{ service_fqdn }}
  environment:
    RANCHER_URL: "{{rancher_master_url}}"
    RANCHER_ACCESS_KEY: "{{ rancher_api_key }}"
    RANCHER_SECRET_KEY: "{{ rancher_api_secret }}"
    RANCHER_ENVIRONMENT: "{{ rancher_project_name }}"
  shell: "rancher scale {{ service_fqdn }}={{ service_scale }}"
  register: scalelog
  become: yes

- debug: var=scalelog.stdout_lines
